EFFECTS_DIRS := \
	$(SRC_DIR)/effects \
	$(SRC_DIR)/effects/basics \
	$(SRC_DIR)/effects/delay \
	$(SRC_DIR)/effects/distortion \
	$(SRC_DIR)/effects/dynamics \
	$(SRC_DIR)/effects/eqs \
	$(SRC_DIR)/effects/filter&tone \
	$(SRC_DIR)/effects/metering \
	$(SRC_DIR)/effects/modulation \
	$(SRC_DIR)/effects/reverb

EFFECTS_SRCS := $(foreach d,$(EFFECTS_DIRS),$(wildcard $(d)/*.c))
EFFECTS_SRCS := $(filter-out $(SRC_DIR)/effects/effects_manager.c,$(EFFECTS_SRCS))

APP_SRCS := \
	$(SDLAPP_DIR)/sdl_app_framework.c \
	$(SRC_DIR)/core/loop/daw_mainthread_wake.c \
	$(SRC_DIR)/core/loop/daw_mainthread_timer.c \
	$(SRC_DIR)/core/loop/daw_mainthread_jobs.c \
	$(SRC_DIR)/core/loop/daw_mainthread_messages.c \
	$(SRC_DIR)/core/loop/daw_mainthread_kernel.c \
	$(SRC_DIR)/core/loop/daw_render_invalidation.c \
	$(SRC_DIR)/app/daw_app_main.c \
	$(SRC_DIR)/app/audio_recording.c \
	$(SRC_DIR)/app/bounce_region.c \
	$(SRC_DIR)/app/main_bounce.c \
	$(SRC_DIR)/app/main_loop_policy.c \
	$(SRC_DIR)/app/main.c \
	$(SRC_DIR)/config/config.c \
	$(SRC_DIR)/config/data_paths.c \
	$(SRC_DIR)/audio/device_sdl.c \
	$(SRC_DIR)/audio/audio_capture_device_sdl.c \
	$(SRC_DIR)/audio/audio_queue.c \
	$(SRC_DIR)/audio/ringbuf.c \
	$(SRC_DIR)/audio/media_clip.c \
	$(SRC_DIR)/audio/wav_writer.c \
	$(SRC_DIR)/audio/media_cache.c \
	$(SRC_DIR)/audio/media_registry.c \
	$(SRC_DIR)/export/daw_pack_export.c \
	$(SRC_DIR)/export/daw_trace_export.c \
	$(SRC_DIR)/export/daw_trace_export_async.c \
	$(SRC_DIR)/engine/audio_source.c \
	$(SRC_DIR)/engine/engine_core.c \
	$(SRC_DIR)/engine/engine_io.c \
	$(SRC_DIR)/engine/engine_fx.c \
	$(SRC_DIR)/engine/engine_transport.c \
	$(SRC_DIR)/engine/engine_tracks.c \
	$(SRC_DIR)/engine/engine_clips.c \
	$(SRC_DIR)/engine/engine_clips_automation.c \
	$(SRC_DIR)/engine/engine_clips_no_overlap.c \
	$(SRC_DIR)/engine/midi.c \
	$(SRC_DIR)/engine/engine_midi_audition.c \
	$(SRC_DIR)/engine/instrument_osc.c \
	$(SRC_DIR)/engine/timeline_contract.c \
	$(SRC_DIR)/engine/engine_audio.c \
	$(SRC_DIR)/engine/engine_meter.c \
	$(SRC_DIR)/engine/engine_scope_host.c \
	$(SRC_DIR)/engine/engine_eq.c \
	$(SRC_DIR)/engine/engine_spectrum.c \
	$(SRC_DIR)/engine/engine_spectrogram.c \
	$(SRC_DIR)/engine/automation.c \
	$(SRC_DIR)/engine/graph.c \
	$(SRC_DIR)/engine/buffer_pool.c \
	$(SRC_DIR)/time/tempo.c \
	$(SRC_DIR)/engine/source_tone.c \
	$(SRC_DIR)/engine/sampler.c \
	$(SRC_DIR)/effects/effects_manager.c \
	$(SRC_DIR)/session/session_document.c \
	$(SRC_DIR)/session/session_validation.c \
	$(SRC_DIR)/session/session_io_write.c \
	$(SRC_DIR)/session/session_io_read.c \
	$(SRC_DIR)/session/session_io_json.c \
	$(SRC_DIR)/session/session_io_read_parse.c \
	$(SRC_DIR)/session/session_io_read_parse_engine.c \
	$(SRC_DIR)/session/session_io_read_parse_effects_panel.c \
	$(SRC_DIR)/session/session_io_read_parse_master_fx.c \
	$(SRC_DIR)/session/session_io_read_parse_track_clips.c \
	$(SRC_DIR)/session/session_io_read_parse_track_fx.c \
	$(SRC_DIR)/session/session_apply.c \
	$(SRC_DIR)/session/project_manager.c \
	$(SRC_DIR)/undo/undo_manager.c \
	$(SRC_DIR)/undo/undo_manager_stack.c \
	$(SRC_DIR)/app/workspace_authoring/daw_workspace_authoring_host.c \
	$(SRC_DIR)/app/workspace_authoring/daw_workspace_authoring_overlay.c \
	$(SRC_DIR)/ui/panes.c \
	$(SRC_DIR)/ui/layout.c \
	$(SRC_DIR)/ui/overlay/layout_modal_overlays.c \
	$(SRC_DIR)/ui/layout_config.c \
	$(SRC_DIR)/ui/library_browser.c \
	$(SRC_DIR)/ui/timeline_waveform.c \
	$(SRC_DIR)/ui/kit_viz_waveform_adapter.c \
	$(SRC_DIR)/ui/kit_viz_fx_preview_adapter.c \
	$(SRC_DIR)/ui/kit_viz_meter_adapter.c \
	$(SRC_DIR)/ui/waveform_render.c \
	$(SRC_DIR)/ui/beat_grid.c \
	$(SRC_DIR)/ui/time_grid.c \
	$(SRC_DIR)/ui/timeline_view.c \
	$(SRC_DIR)/ui/overlay/timeline_view_overlays.c \
	$(SRC_DIR)/ui/timeline_view_clip_pass.c \
	$(SRC_DIR)/ui/timeline_midi_clip_preview.c \
	$(SRC_DIR)/ui/timeline_view_grid.c \
	$(SRC_DIR)/ui/timeline_view_controls.c \
	$(SRC_DIR)/ui/overlay/timeline_view_runtime_overlays.c \
	$(SRC_DIR)/ui/font.c \
	$(SRC_DIR)/ui/font_bridge.c \
	$(SRC_DIR)/ui/shared_theme_font_adapter.c \
	$(SRC_DIR)/ui/text_draw.c \
	$(SRC_DIR)/ui/transport.c \
	$(SRC_DIR)/ui/clip_inspector.c \
	$(SRC_DIR)/ui/clip_inspector_controls.c \
	$(SRC_DIR)/ui/clip_inspector_waveform.c \
	$(SRC_DIR)/ui/midi_editor.c \
	$(SRC_DIR)/ui/midi_editor_pitch_view.c \
	$(SRC_DIR)/ui/midi_preset_browser.c \
	$(SRC_DIR)/ui/midi_instrument_panel.c \
	$(SRC_DIR)/ui/effects_panel/panel.c \
	$(SRC_DIR)/ui/effects_panel/sync.c \
	$(SRC_DIR)/ui/effects_panel/overlay.c \
	$(SRC_DIR)/ui/effects_panel/state_helpers.c \
	$(SRC_DIR)/ui/effects_panel/slot_view.c \
	$(SRC_DIR)/ui/effects_panel/slot_preview.c \
	$(SRC_DIR)/ui/effects_panel/slot_preview_delay.c \
	$(SRC_DIR)/ui/effects_panel/slot_preview_time_domain.c \
	$(SRC_DIR)/ui/effects_panel/slot_preview_eq_curve.c \
	$(SRC_DIR)/ui/effects_panel/slot_layout.c \
	$(SRC_DIR)/ui/effects_panel/slot_widgets.c \
	$(SRC_DIR)/ui/effects_panel/spec_panel.c \
	$(SRC_DIR)/ui/effects_panel/spec_panel_render.c \
	$(SRC_DIR)/ui/effects_panel/list_view.c \
	$(SRC_DIR)/ui/effects_panel/eq_detail_view.c \
	$(SRC_DIR)/ui/effects_panel/meter_detail_view.c \
	$(SRC_DIR)/ui/effects_panel/meter_detail_history_grid.c \
	$(SRC_DIR)/ui/effects_panel/meter_detail_history_cache.c \
	$(SRC_DIR)/ui/effects_panel/meter_detail_correlation.c \
	$(SRC_DIR)/ui/effects_panel/meter_detail_levels.c \
	$(SRC_DIR)/ui/effects_panel/meter_detail_lufs.c \
	$(SRC_DIR)/ui/effects_panel/meter_detail_mid_side.c \
	$(SRC_DIR)/ui/effects_panel/meter_detail_spectrogram.c \
	$(SRC_DIR)/ui/effects_panel/meter_detail_vectorscope.c \
	$(SRC_DIR)/ui/effects_panel/track_snapshot_view.c \
	$(SRC_DIR)/input/input_manager.c \
	$(SRC_DIR)/input/library_input.c \
	$(SRC_DIR)/input/timeline/timeline_clipboard.c \
	$(SRC_DIR)/input/timeline/timeline_drop.c \
	$(SRC_DIR)/input/timeline/timeline_geometry.c \
	$(SRC_DIR)/input/timeline/timeline_input.c \
	$(SRC_DIR)/input/timeline/timeline_input_keyboard.c \
	$(SRC_DIR)/input/timeline/timeline_input_mouse.c \
	$(SRC_DIR)/input/timeline/timeline_input_mouse_click.c \
	$(SRC_DIR)/input/timeline/timeline_input_mouse_clip_press.c \
	$(SRC_DIR)/input/timeline/timeline_input_mouse_tempo_overlay.c \
	$(SRC_DIR)/input/timeline/timeline_input_mouse_drag.c \
	$(SRC_DIR)/input/timeline/timeline_input_mouse_scroll.c \
	$(SRC_DIR)/input/timeline/timeline_clip_helpers.c \
	$(SRC_DIR)/input/timeline/timeline_midi_region.c \
	$(SRC_DIR)/input/timeline/timeline_midi_trim.c \
	$(SRC_DIR)/input/timeline/timeline_snap.c \
	$(SRC_DIR)/input/timeline/timeline_selection.c \
	$(SRC_DIR)/input/timeline/timeline_drag.c \
	$(SRC_DIR)/input/automation_input.c \
	$(SRC_DIR)/input/tempo_overlay_input.c \
	$(SRC_DIR)/input/inspector_input.c \
	$(SRC_DIR)/input/inspector_input_numeric_edit.c \
	$(SRC_DIR)/input/inspector_fade_input.c \
	$(SRC_DIR)/input/midi_editor_input.c \
	$(SRC_DIR)/input/midi_editor_input_selection.c \
	$(SRC_DIR)/input/midi_editor_input_timing.c \
	$(SRC_DIR)/input/midi_editor_input_commands.c \
	$(SRC_DIR)/input/midi_editor_input_qwerty.c \
	$(SRC_DIR)/input/midi_editor_input_gestures.c \
	$(SRC_DIR)/input/midi_instrument_panel_input.c \
	$(SRC_DIR)/input/transport_input.c \
	$(SRC_DIR)/input/effects_panel_input.c \
	$(SRC_DIR)/input/effects_panel_input_helpers.c \
	$(SRC_DIR)/input/effects_panel_eq_detail_input.c \
	$(SRC_DIR)/input/effects_panel_track_snapshot.c \
	$(SRC_DIR)/render/adapters/timer_hud_adapter.c \
	$(EFFECTS_SRCS)

TIMER_HUD_SRCS := $(shell find $(TIMER_HUD_DIR)/src -type f -name '*.c')
TIMER_HUD_EXTERNAL_SRCS := $(TIMER_HUD_DIR)/external/cJSON.c
TIMER_HUD_SUPPORT_SRCS := $(TIMER_HUD_SRCS) $(TIMER_HUD_EXTERNAL_SRCS)
