TARGET_CONTRACT_HELPER ?= $(abspath tools/desktop_release_target_contract.sh)
TARGET_CONTRACT_HELPER_CMD = /bin/sh "$(TARGET_CONTRACT_HELPER)"
HOST_ARCH := $(strip $(shell $(TARGET_CONTRACT_HELPER_CMD) get host_arch))
TARGET_OS_INPUT := $(TARGET_OS)
TARGET_ARCH_INPUT := $(TARGET_ARCH)
TARGET_VARIANT_INPUT := $(TARGET_VARIANT)
TARGET_OS ?= $(strip $(shell TARGET_OS="$(TARGET_OS_INPUT)" TARGET_ARCH="$(TARGET_ARCH_INPUT)" TARGET_VARIANT="$(TARGET_VARIANT_INPUT)" $(TARGET_CONTRACT_HELPER_CMD) get target_os))
TARGET_ARCH ?= $(strip $(shell TARGET_OS="$(TARGET_OS_INPUT)" TARGET_ARCH="$(TARGET_ARCH_INPUT)" TARGET_VARIANT="$(TARGET_VARIANT_INPUT)" $(TARGET_CONTRACT_HELPER_CMD) get target_arch))
TARGET_VARIANT ?= $(strip $(shell TARGET_OS="$(TARGET_OS_INPUT)" TARGET_ARCH="$(TARGET_ARCH_INPUT)" TARGET_VARIANT="$(TARGET_VARIANT_INPUT)" $(TARGET_CONTRACT_HELPER_CMD) get target_variant))
TARGET_TRIPLE := $(strip $(shell TARGET_OS="$(TARGET_OS)" TARGET_ARCH="$(TARGET_ARCH)" TARGET_VARIANT="$(TARGET_VARIANT)" $(TARGET_CONTRACT_HELPER_CMD) get target_triple))
RELEASE_PLATFORM := $(strip $(shell TARGET_OS="$(TARGET_OS)" TARGET_ARCH="$(TARGET_ARCH)" TARGET_VARIANT="$(TARGET_VARIANT)" $(TARGET_CONTRACT_HELPER_CMD) get release_platform))
RELEASE_ARCH := $(strip $(shell TARGET_OS="$(TARGET_OS)" TARGET_ARCH="$(TARGET_ARCH)" TARGET_VARIANT="$(TARGET_VARIANT)" $(TARGET_CONTRACT_HELPER_CMD) get release_arch))
TARGET_HOMEBREW_PREFIX ?= $(strip $(shell TARGET_OS="$(TARGET_OS)" TARGET_ARCH="$(TARGET_ARCH)" TARGET_VARIANT="$(TARGET_VARIANT)" $(TARGET_CONTRACT_HELPER_CMD) get homebrew_prefix))
TARGET_ALT_HOMEBREW_PREFIX ?= $(strip $(shell TARGET_OS="$(TARGET_OS)" TARGET_ARCH="$(TARGET_ARCH)" TARGET_VARIANT="$(TARGET_VARIANT)" $(TARGET_CONTRACT_HELPER_CMD) get alt_homebrew_prefix))
TARGET_PKG_CONFIG_LIBDIR ?= $(TARGET_HOMEBREW_PREFIX)/lib/pkgconfig:$(TARGET_HOMEBREW_PREFIX)/share/pkgconfig
TARGET_DEP_SEARCH_ROOTS ?= $(TARGET_HOMEBREW_PREFIX):$(TARGET_ALT_HOMEBREW_PREFIX)
ARCH_FLAGS := -arch $(TARGET_ARCH)

ifeq ($(BUILD_TOOLCHAIN),clang)
APP_CC := $(HOST_CC)
TOOLCHAIN_DEP :=
else ifeq ($(BUILD_TOOLCHAIN),fisics)
APP_CC := $(FISICS_CC)
TOOLCHAIN_DEP := $(FISICS_CC)
else
$(error Unsupported BUILD_TOOLCHAIN '$(BUILD_TOOLCHAIN)'; expected clang or fisics)
endif
